INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (1,"Nintendo"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (2,"Microsoft Studios"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (3,"Activision"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (4,"Sony"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (5,"Sega"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (6,"Capcom"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (7,"Rockstar Games"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (8,"Bethesda Game Studios"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (9,"Psyonix"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (10,"Riot games"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (11,"Ubisoft"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (12,"Mojang studios"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (13,"Blizzard Entertainment"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (14,"Epic games"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (15,"EA"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (16,"Valve"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (17,"THQ"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (18,"Capcom"),
INSERT INTO desarrollador(id_desarrollador, desarrollador) VALUES (19,"Konami");
