INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (1,'Danish'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (2,'Dominicano'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (3,'Ecuadorio'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (4,'Mexicano'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (5,'Gringo'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (6,'Alemania'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (7,'Indio'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (8,'Iraqia'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (9,'Britiania'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (10,'Japones'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (11,'Mongolio'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (12,'Dutch'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (13,'Surth Koreano'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (14,'Portuguese'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (15,'Africa'),
INSERT INTO nacionalidad(id_nacionalidad, nacionalidad) VALUES (16,'Espaniol');